/** @format */
export const DataHome = [
  {
    name: "trending now",
    data: [
      {
        name: "The Seven Deadly Sins: Wrath of the Gods",
        type: [{ name: "Active" }, { name: "Movie" }],
        view: 9141,
        comment: 11,
        current_episodes: 17,
        episodes: 18,
        url: "https://technext.github.io/anime/img/trending/trend-1.jpg",
      },
      {
        name: "Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien",
        type: [{ name: "Active" }, { name: "Movie" }],
        view: 9141,
        comment: 11,
        current_episodes: 17,
        episodes: 18,
        url: "https://technext.github.io/anime/img/trending/trend-2.jpg",
      },
      {
        name: "Shingeki no Kyojin Season 3 Part 2",
        type: [{ name: "Active" }, { name: "Movie" }],
        view: 9141,
        comment: 11,
        current_episodes: 17,
        episodes: 18,
        url: "https://technext.github.io/anime/img/trending/trend-3.jpg",
      },
      {
        name: "Fullmetal Alchemist: Brotherhood",
        type: [{ name: "Active" }, { name: "Movie" }],
        view: 9141,
        comment: 11,
        current_episodes: 17,
        episodes: 18,
        url: "https://technext.github.io/anime/img/trending/trend-4.jpg",
      },
      {
        name: "Shiratorizawa Gakuen Koukou",
        type: [{ name: "Active" }, { name: "Movie" }],
        view: 9141,
        comment: 11,
        current_episodes: 17,
        episodes: 18,
        url: "https://technext.github.io/anime/img/trending/trend-5.jpg",
      },
      {
        name: "Code Geass: Hangyaku no Lelouch R2",
        type: [{ name: "Active" }, { name: "Movie" }],
        view: 9141,
        comment: 11,
        current_episodes: 17,
        episodes: 18,
        url: "https://technext.github.io/anime/img/trending/trend-6.jpg",
      },
    ],
  },
  {
    name: "Popular Shows",
    data: [
      {
        name: "Sen to Chihiro no Kamikakushi",
        type: [{ name: "Active" }, { name: "Movie" }],
        view: 9141,
        comment: 11,
        current_episodes: 17,
        episodes: 18,
        url: "https://technext.github.io/anime/img/popular/popular-1.jpg",
      },
      {
        name: "Kizumonogatari III: Reiket su-hen",
        type: [{ name: "Active" }, { name: "Movie" }],
        view: 9141,
        comment: 11,
        current_episodes: 17,
        episodes: 18,
        url: "https://technext.github.io/anime/img/popular/popular-2.jpg",
      },
      {
        name: "Shirogane Tamashii hen Kouhan sen",
        type: [{ name: "Active" }, { name: "Movie" }],
        view: 9141,
        comment: 11,
        current_episodes: 17,
        episodes: 18,
        url: "https://technext.github.io/anime/img/popular/popular-3.jpg",
      },
      {
        name: "Rurouni Kenshin: Meiji Kenkaku Romantan",
        type: [{ name: "Active" }, { name: "Movie" }],
        view: 9141,
        comment: 11,
        current_episodes: 17,
        episodes: 18,
        url: "https://technext.github.io/anime/img/popular/popular-4.jpg",
      },
      {
        name: "Mushishi Zoku Shou 2nd Season",
        type: [{ name: "Active" }, { name: "Movie" }],
        view: 9141,
        comment: 11,
        current_episodes: 17,
        episodes: 18,
        url: "https://technext.github.io/anime/img/popular/popular-5.jpg",
      },
      {
        name: "Monogatari Series: Second Season",
        type: [{ name: "Active" }, { name: "Movie" }],
        view: 9141,
        comment: 11,
        current_episodes: 17,
        episodes: 18,
        url: "https://technext.github.io/anime/img/popular/popular-6.jpg",
      },
    ],
  },
  {
    name: "Recently Added Shows",
    data: [
      {
        name: "Great Teacher Onizuka",
        type: [{ name: "Active" }, { name: "Movie" }],
        view: 9141,
        comment: 11,
        current_episodes: 17,
        episodes: 18,
        url: "https://technext.github.io/anime/img/recent/recent-1.jpg",
      },
      {
        name: "Fate/stay night Movie: Heaven's Feel - II. Lost",
        type: [{ name: "Active" }, { name: "Movie" }],
        view: 9141,
        comment: 11,
        current_episodes: 17,
        episodes: 18,
        url: "https://technext.github.io/anime/img/recent/recent-2.jpg",
      },
      {
        name: "Mushishi Zoku Shou: Suzu no Shizuku",
        type: [{ name: "Active" }, { name: "Movie" }],
        view: 9141,
        comment: 11,
        current_episodes: 17,
        episodes: 18,
        url: "https://technext.github.io/anime/img/recent/recent-3.jpg",
      },
      {
        name: "Fate/Zero 2nd Season",
        type: [{ name: "Active" }, { name: "Movie" }],
        view: 9141,
        comment: 11,
        current_episodes: 17,
        episodes: 18,
        url: "https://technext.github.io/anime/img/recent/recent-4.jpg",
      },
      {
        name: "Kizumonogatari II: Nekket su-hen",
        type: [{ name: "Active" }, { name: "Movie" }],
        view: 9141,
        comment: 11,
        current_episodes: 17,
        episodes: 18,
        url: "https://technext.github.io/anime/img/recent/recent-5.jpg",
      },
      {
        name: "The Seven Deadly Sins: Wrath of the Gods",
        type: [{ name: "Active" }, { name: "Movie" }],
        view: 9141,
        comment: 11,
        current_episodes: 17,
        episodes: 18,
        url: "https://technext.github.io/anime/img/recent/recent-6.jpg",
      },
    ],
  },
  {
    name: "Live Action",
    data: [
      {
        name: "Shouwa Genroku Rakugo Shinjuu",
        type: [{ name: "Active" }, { name: "Movie" }],
        view: 9141,
        comment: 11,
        current_episodes: 17,
        episodes: 18,
        url: "https://technext.github.io/anime/img/live/live-1.jpg",
      },
      {
        name: "Mushishi Zoku Shou 2nd Season",
        type: [{ name: "Active" }, { name: "Movie" }],
        view: 9141,
        comment: 11,
        current_episodes: 17,
        episodes: 18,
        url: "https://technext.github.io/anime/img/live/live-2.jpg",
      },
      {
        name: "Mushishi Zoku Shou: Suzu no Shizuku",
        type: [{ name: "Active" }, { name: "Movie" }],
        view: 9141,
        comment: 11,
        current_episodes: 17,
        episodes: 18,
        url: "https://technext.github.io/anime/img/live/live-3.jpg",
      },
      {
        name: "The Seven Deadly Sins: Wrath of the Gods",
        type: [{ name: "Active" }, { name: "Movie" }],
        view: 9141,
        comment: 11,
        current_episodes: 17,
        episodes: 18,
        url: "https://technext.github.io/anime/img/live/live-4.jpg",
      },
      {
        name: "Fate/stay night Movie: Heaven's Feel - II. Lost",
        type: [{ name: "Active" }, { name: "Movie" }],
        view: 9141,
        comment: 11,
        current_episodes: 17,
        episodes: 18,
        url: "https://technext.github.io/anime/img/live/live-5.jpg",
      },
      {
        name: "Kizumonogatari II: Nekketsu-hen",
        type: [{ name: "Active" }, { name: "Movie" }],
        view: 9141,
        comment: 11,
        current_episodes: 17,
        episodes: 18,
        url: "https://technext.github.io/anime/img/live/live-6.jpg",
      },
    ],
  },
];
